[tool.black]
line-length = 79
target-version = ["py36", "py37", "py38", "py39", "py310"]

[tool.ruff]
line-length = 79
target-version = "py37"
select = ["E", "F", "B"]
ignore = [
    "E50", # Black
    "E70", # Black

]
fix = true

[tool.ruff.isort]
known-first-party = ["conftest"]
known-third-party = ["pexpect", "pytest"]
