[tool.ruff]
line-length = 79
target-version = "py37"
lint.select = ["E", "F", "B"]
lint.ignore = [
    # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    # (keep order of ignores here same as ^there for maintainability)
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "E501",
]
fix = true

[tool.ruff.lint.isort]
known-first-party = ["conftest"]
known-third-party = ["pexpect", "pytest"]
